newspaper_bills/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

newspaper_bills/bill_manager/urls.py
from django.urls import path
from . import views

app_name = 'bill_manager'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('plan/<int:pk>/', views.Plan.as_view(), name='plan'),
    path('edit_plan/<int:pk>/', views.EditPlan.as_view(), name='edit_plan'),
    path('my_bills/', views.MyBills.as_view(), name='my_bills'),
    path('bill/<int:pk>/', views.Bill.as_view(), name='bill'),
    path('create_plan/', views.NewPlan.as_view(), name='create_plan'),
]

newspaper_bills/feedbacks/urls.py
from django.urls import path
from . import views


app_name = 'feedbacks'
urlpatterns = [
    path('', views.FeedbackView.as_view(), name='feedback_form'),
]

newspaper_bills/newspaper_bills/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bill_manager/', include('bill_manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('feedback/', include('feedbacks.urls')),
    path('summernote/', include('django_summernote.urls')),
]

HOME = 'bill_manager:home'

newspaper_bills/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block Title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block Css %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="text: solid white;">
    <a class="navbar-brand" href="#">Newspapers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                {% url 'bill_manager:home' as home %}
                {% if request.path == home %}
                    <li class="nav-item active">
                        <a class="nav-link">Home</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bill_manager:home' %}">Home</a>
                    </li>
                {% endif %}
            
                {% url 'bill_manager:create_plan' as new_plan %}
                {% if request.path != new_plan %}
                    {% url 'bill_manager:plan' request.user.plan_id as plan %}
                    {% if request.path == plan %}
                        <li class="nav-item active">
                            <a class="nav-link">My Plan</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bill_manager:plan' request.user.plan_id %}">
                                My Plan
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
            
                {% url 'bill_manager:my_bills' as my_bills %}
                {% if request.path == my_bills %}
                    <li class="nav-item active">
                        <a class="nav-link active">My Bills</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bill_manager:my_bills' %}">
                            My Bills
                        </a>
                    </li>
                {% endif %}
            
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">
                        Logout<br>
                    </a>
                </li>
            
                {% url 'feedbacks:feedback_form' as feedback %}
                {% if request.path == feedback %}
                    <li class="nav-item"><a class="nav-link active">
                        Feedback
                    </a></li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'feedbacks:feedback_form' %}">
                            Feedback
                        </a>
                    </li>
                {% endif %}
            
            {% else %}
                {% url 'accounts:signup' as signup %}
                {% if request.path == signup %}
                    <li class="nav-item"><a class="nav-link active">
                        Sign Up
                    </a></li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">
                            Signup
                        </a>
                    </li>
                {% endif %}
            
                {% url 'login' as login %}
                {% if request.path == login %}
                    <li class="nav-item"><a class="nav-link active">
                        Log In
                    </a></li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">
                            Log In
                        </a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
</nav>

{% for message in messages %}
    {{message}}
{% endfor %}
{% block Content %}
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% block Js %}
{% endblock %}

<footer class="page-footer font-small blue">
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="http://127.0.0.1:8000/bill_manager/"> Newspapers.com</a>
    </div>
</footer>

</body>
</html>

newspaper_bills/templates/bill.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
Bill-{{bill.id}}
{% endblock %}

{% block Css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bill.css' %}">
{% endblock %}

{% block Content %}
<div class="text-center">
    <div class="row justify-content-center">
        <div class="details col-3">
        <strong>Bill id:</strong> {{bill.id}}<br>
        <strong>Month: </strong>{{month_name}}, {{year}}<br>
            <strong>Amount: Rs. <span class="text-monospace" style="color:red;">{{bill.amount}}</span></strong><br>
        <strong>Paid on: </strong>
            {% if bill.status is None and bill.current == False %}
            <strong>Unpaid</strong>
            <form method="post" action="{% url 'bill_manager:bill' %}">
                {% csrf_token %}
                <button type="submit" name="mark_as_paid" value="{{bill.id}}">Mark as paid</button>
            </form>
            {% elif bill.current == True %}
                The month is not over yet.
            {% else %}
            {{bill.status}}
            {% endif %}
        </div>
    </div>
    
    <div class="row justify-content-center">
        <div class="calendar row justify-content-center col-3">
            <table>
                <thead>
                    <tr>
                       <th>Sun</th>
                       <th>Mon</th>
                       <th>Tue</th>
                       <th>Wed</th>
                       <th>Thu</th>
                       <th>Fri</th>
                       <th>Sat</th>
                    </tr>
                </thead>
                <tbody>
                {% for i in calendar_rows %}
                    <tr>
                        {% for i in 1|rjust:7 %}
                            {% if counter.value <= 0 or counter.value > days %}
                                <td> </td>
                            {% else %}
                                {% if counter.value <= day %}
                                <td>
                                    {% if counter.value in bill.absentees %}
                                        <button type="submit" name="date" class="btn btn-danger btn-block disabled" value="{{counter.value}}">
                                            {{counter.value}}
                                        </button>
                                    {% else %}
                                        <button type="submit" name="date" class="btn btn-primary btn-block disabled" value="{{counter.value}}">
                                            {{counter.value}}
                                        </button>
                                    {% endif %}
            <!--                    <br>-->
                                </td>
                                {% else %}
                                <td><button type="submit" name="date" class="btn btn-dark disabled col-12" value="{{counter.value}}">
                                    {{counter.value}}
                                </button></td>
                            {% endif %}
                            {% endif %}
                            {{ counter.increment }}
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

newspaper_bills/templates/edit_plan.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block Title %}
Edit Plan
{% endblock %}

{% block Css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/edit_plan.css' %}">
{% endblock %}

{% block Content %}
<div class="text-center">
    <div class="heading">
        <h3>Edit Your Plan</h3>
    </div>
    
    <div class="row justify-content-center">
        <div class="edit_form col-2">
            <form method="post" action="{% url 'bill_manager:edit_plan' request.user.plan_id %}">
            {% csrf_token %}
                {% for field in form %}
                    <div class="form-group row form-control-sm">
                        <div class="text-danger">
                        {% for error in field.errors %}
                            <i class="fas fa-exclamation-triangle"></i>
                           {{error|escape}}
                        {% endfor %}
                        </div>
                        
                        <label class="col-sm-2 col-form-label">{{field.label_tag}}</label>
    
                        <div class="col-sm-10">
                            {% render_field field class="form-control" %}
                        </div>
                        <small class="form-text text-muted">
                            {{ field.help_text }}
                            </small>
                     </div>
                {% endfor %}
                
            <button type="submit" class="btn btn-primary col-12">Save Plan</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

newspaper_bills/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
Home
{% endblock %}

{% block Css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block Content %}
<div class="text-center">
    <div class="heading">
        <h3>{{month_name}}, {{year}}</h3>
        your net bill for the month, till date is <strong>Rs. {{amount}}</strong>.<br><br><br>
    </div>
    
    <div class="row justify-content-center">
    <div class="calendar row justify-content-center col-3">
        <form method="post" action="{% url 'bill_manager:home' %}">
            {% csrf_token %}
        <table>
            <thead>
                <tr>
                   <th>Sun</th>
                   <th>Mon</th>
                   <th>Tue</th>
                   <th>Wed</th>
                   <th>Thu</th>
                   <th>Fri</th>
                   <th>Sat</th>
                </tr>
            </thead>
            <tbody>
            {% for i in calendar_rows %}
                <tr>
                    {% for i in 1|rjust:7 %}
                        {% if counter.value <= 0 or counter.value > days %}
                            <td> </td>
                        {% else %}
                            {% if counter.value <= day %}
                            <td>
                                {% if counter.value in absentees %}
                                    <button type="submit" name="date" class="btn btn-danger btn-block btn-lg col-12" value="{{counter.value}}">
                                        {{counter.value}}
                                    </button>
                                {% else %}
                                    <button type="submit" name="date" class="btn btn-primary btn-block col-12 btn-lg" value="{{counter.value}}">
                                        {{counter.value}}
                                    </button>
                                {% endif %}
        <!--                    <br>-->
                            </td>
                            {% else %}
                            <td><button type="submit" name="date" class="btn btn-dark disabled col-12 btn-lg" value="{{counter.value}}">
                                {{counter.value}}
                            </button></td>
                        {% endif %}
                        {% endif %}
                        {{ counter.increment }}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table></form><br>
    </div>
    </div>
</div>
{% endblock %}

newspaper_bills/templates/my_bills.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
My Bills
{% endblock %}

{% block Css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/my_bills.css' %}">
{% endblock %}

{% block Content %}<br>
<div class="text-center">
    <div class="heading">
        <h3>You Newspaper Bills</h3>
    </div>
    
    <div class="row justify-content-center">
        <div class="bills">
            <table class="table-hover">
                <thead>
                <tr>
                    <th style="padding: 0px 20px 0px 20px;">Serial No.</th>
                    <th style="padding: 0px 20px 0px 20px;">Month</th>
                    <th style="padding: 0px 20px 0px 20px;">Amount</th>
                    <th style="padding: 0px 20px 0px 20px;">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for bill_ in user_bills %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{% url 'bill_manager:bill' bill_.id %}" class="text-decoration-none">
                        {{bill_.month_name}}, {{bill_.year}}
                    </a></td>
                    <td class="text-monospace">{{bill_.amount}}</td>
                    {% if bill_.paid_on is None %}
                    <td><span class="text-danger">Unpaid</span></td>
                    {% else %}
                    <td><span class="text-muted text-sm">Paid on:   </span>
                        <span class="text-monospace">{{bill_.paid_on}}</span></td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

newspaper_bills/templates/new_plan.html
{% extends 'base.html' %}

{% block Title %}
Create New Plan
{% endblock %}

{% block Content %}
<h3>Upload your newspaper plan</h3>
<form method="post" action="{% url 'bill_manager:create_plan' %}">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Upload Plan</button>
</form>
{% endblock %}

newspaper_bills/templates/plan.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
My Plan
{% endblock %}

{% block Css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/plan.css' %}">
{% endblock %}

{% block Content %}
<div class="text-center">
    <div class="heading">
        <h3>Your Newspaper Plan</h3>
    </div>
    
    <div class="row justify-content-center">
        <div class="plan">
            <table class="plan-table table-striped table-reflow">
                <thead>
                    <tr>
                        <th style="padding: 0px 25px 0px 25px;">Day</th>
                        <th style="padding: 0px 25px 0px 25px;">Cost of Newspaper (Rs)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Sun</strong></td>
                        <td>{{object.sun}}</td>
                    </tr>
                    <tr>
                        <td>Mon</td>
                        <td>{{object.mon}}</td>
                    </tr>
                    <tr>
                        <td>Tue</td>
                        <td>{{object.tue}}</td>
                    </tr>
                    <tr>
                        <td>Wed</td>
                        <td>{{object.wed}}</td>
                    </tr>
                    <tr>
                        <td>Thu</td>
                        <td>{{object.thu}}</td>
                    </tr>
                    <tr>
                        <td>Fri</td>
                        <td>{{object.fri}}</td>
                    </tr>
                    <tr>
                        <td><strong>Sat</strong></td>
                        <td>{{object.sat}}</td>
                    </tr>
                </tbody>
            </table><br>
            <form method="post" action="{% url 'bill_manager:plan' object.id %}">
                {% csrf_token %}
                <button name="edit_plan" class="btn btn-primary col-12" formmethod="post">Edit Plan</button>
            </form>
        </div>
    </div>
    
</div>
{% endblock %}

newspaper_bills/templates/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block Title %}
SignUp
{% endblock %}

{% block Css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block Content %}
<div class="text-center">
    <div class="heading">
        <h3>Signup</h3>
    </div>
    
    <div class="row justify-content-center">
        <div class="signup_form col-4">
            <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{field.label_tag}}
            
                    <div class="text-danger">
                    {% for error in field.errors %}
                        <i class="fas fa-exclamation-triangle"></i>
                        {{error|escape}}
                    {% endfor %}
                    </div>
    
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {% render_field field class="form-control" %}
            
                        <small class="form-text text-muted">
                        {{ field.help_text }}
                        </small>
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary col-12">Sign-Up</button>
            </form>
        </div>
    </div><br>
Already have an account? Login <a href="{% url 'login' %}">here</a>.
</div>
{% endblock %}